apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hello-world
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-hello-world
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50